In [2]:
# tensor is a data structure that very similar to arrays and matrices
# we use tensors as inputs, outputs and parameters
# tensors can share memory with numpy

import torch
import numpy as np

In [3]:
# tensors

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
# tensors can be created by NumPy

np_array = np.array(data)
x_np = torch.from_numpy(np_array)


In [6]:
# can create tensor from another tensor

#generate a tensor with same shape and type with x_data and all elements is 1
x_ones = torch.ones_like(x_data)

# classic python sentence -- formatted string (f-string)
print(f"Ones Tensor: \n {x_ones} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [7]:
# generate random float numbers
x_rand = torch.rand_like(x_data, dtype=torch.float)
# here is a override dtype should be x_data_dtype
print(f"random tensor: \n {x_rand} \n")

random tensor: 
 tensor([[0.5575, 0.9714],
        [0.8735, 0.0262]]) 



In [9]:
# This actually define a 2d array
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")


random tensor: 
 tensor([[0.9167, 0.4304, 0.4237],
        [0.2515, 0.3694, 0.1977]]) 

ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [10]:
# attributes of a tensor includes shape, datatype and the divice on which they are stored

tensor = torch.rand(3,4)

print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")


shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [12]:
# pytroch并不是默认使用GPU
if torch.accelerator.is_available(): #当前环境有无可用加速器
    tensor = tensor.to(torch.accelerator.current_accelerator())
#.to切换加速器

In [13]:
print(tensor.device)


mps:0


In [14]:
#most of tensor movements are same with numpy
# standard numpy-like indexing and slicing
tensor = torch.ones(4,4)
print(f"first row: {tensor[0]}")
print(f"first column: {tensor[:, 0]}")
print(f"last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

# 数组操作中基本0是第一个，1是第二个，-1是最后一个

first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
# 沿着列向量拼起来，0是行，1是列
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
print(t1.shape)
# 按列拼接的意思是拼接后使列维度增长
# 或者说dim=1这个维度的size相加，dim=0的维度size不变

torch.Size([4, 12])


In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T #matrix multiplication
y2 = tensor.matmul(tensor.T) #matrix multiplication

y3 = torch.rand_like(y1) #random matrix with same shape
torch.matmul(tensor, tensor.T, out=y3) #matrix multiplication


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor) #element-wise multiplication

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

In [19]:
# Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():
# use item() to transfer a python class

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [20]:
# 带下划线的一般是自加自减之类的操作 （in-place）
# in-place操作会节省一些内存，但在计算导数时会bug，所以不鼓励用
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [22]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

#pytorch在cpu tensor的底层是一段连续内存，numpy也是，可以直接共享内存
#但在GPU上不行，因为物理现实就不是连续的

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [24]:
# 改变torch也会改变numpy，因为用的是一块内存
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [25]:
# numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)


In [26]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
